### ISSUE TITLE
multipers has no attribute 'simplex_tree_multi'

### ISSUE THREAD

**Issue by jmou19** [DavidLapous/multipers#11]
Hello, 

I'm attempting to read through the _multipers_introduction_ notebook, and I am receiving an error when running the following block near line 27: 

```
# In practice, it is recommended to not use the sparse parameter, as there is not theoretical guarantees in this case.
(simplextree,), = mmp.PointCloud2SimplexTree(expand_dim=2,bandwidths=[0.2], num_collapses="full", sparse=.1, threshold=2, complex='rips').fit_transform([X])
```

The entire error is given below in form of a screenshot. 
![image](https://github.com/DavidLapous/multipers/assets/87163744/596f0367-b5f0-41d9-bcd3-c833405a7966)

I have version 1.2.2 of multipers installed. Please let me know if I can provide any further information about my set up to assist in diagnosing the problem.

**Comment by jmou19** [comment]
I resolved the issue by running the recommended command at the top of the notebook:

```
 mp.simplex_tree_multi.SAFE_CONVERSION=True ## Enable this if you encounter crashes.
```

**Comment by DavidLapous** [comment]
Hmm this line shouldn't fix this issue, so there's still a bug somewhere, thanks for noticing it.
I'm glad that you could fix this though :+1: 

I'm currently rewriting the simplextree module, so I hope this will disappear with this 😇
