### ISSUE TITLE
Contributor instructions

### ISSUE THREAD

**Issue by peekxc** [DavidLapous/multipers#19]
Per the JOSS standard, there should be some community guidelines regarding contribution, reporting issues, etc. The examples in the package are great, but I didn't find either a CONTRIBUTING.md or a doc page [akin to this](https://www.pandoc.org/CONTRIBUTING.html) giving such instructions. 

@DavidLapous Could you add one of the above to the repo, or show me where one already exists? It would help potential contributors immensely!

[6773](https://github.com/openjournals/joss-reviews/issues/6773)

**Comment by DavidLapous** [comment]
There is a small section already at the end of the readme, and I've added templates for issues / feature requests in the commits 0e4878461ae0286efea39aa0f6e6325f9e8c61c7 and 2d7287612a494eb0ebfb922c1803a48187089d73.
You can check that by trying to open an issue. I'll add a contributing page in the documentation for the next release.

**Comment by DavidLapous** [comment]
I've added a contributions page in the doc [here](https://www-sop.inria.fr/members/David.Loiseaux/doc/multipers/contributions.html). I still need to do a release to ensure that doc<->library are coherent, but this point should be fixed.

**Comment by peekxc** [comment]
Thanks @DavidLapous! Looks good
